In [2]:
import os
import hashlib
from pathlib import Path
import pandas as pd

In [3]:
INPUT_DIR = Path("../data/input_pdfs")

pdf_files = sorted(INPUT_DIR.glob("*.pdf"))

print(f"Found {len(pdf_files)} PDF(s).")

for pdf in pdf_files:
    print(pdf.name)

Found 3 PDF(s).
sample_pdf_1.pdf
sample_pdf_2.pdf
sample_pdf_3.pdf

In [4]:
def generate_hash(filepath):
    hasher = hashlib.sha256()

    with open(filepath, "rb") as f:
        while chunk := f.read(8192):
            hasher.update(chunk)

    return hasher.hexdigest()

In [5]:
records = []

for pdf in pdf_files:

    size_mb = pdf.stat().st_size / (1024 * 1024)

    records.append({
        "file name": pdf.name,
        "file path": str(pdf),
        "size": round(size_mb,2),
        "hash": generate_hash(pdf),
        "status": "Pending"
    })

inventory = pd.DataFrame(records)

inventory

,file name,file path,size,hash,status
0,sample_pdf_1.pdf,..\data\input_pdfs\sample_pdf_1.pdf,0.76,a97c1e61377a41e3b6315243a002d8f1d222c5e951ebab...,Pending
1,sample_pdf_2.pdf,..\data\input_pdfs\sample_pdf_2.pdf,0.63,cc441c9b5aea97fafde23cd2c5a9a66b1a53edea0d1eae...,Pending
2,sample_pdf_3.pdf,..\data\input_pdfs\sample_pdf_3.pdf,0.06,8264bbd9bc2afc3c4ce9f04ba2cde4f82abff6f56ae446...,Pending

In [6]:
inventory = inventory.drop_duplicates(subset="hash").reset_index(drop=True)
inventory

,file name,file path,size,hash,status
0,sample_pdf_1.pdf,..\data\input_pdfs\sample_pdf_1.pdf,0.76,a97c1e61377a41e3b6315243a002d8f1d222c5e951ebab...,Pending
1,sample_pdf_2.pdf,..\data\input_pdfs\sample_pdf_2.pdf,0.63,cc441c9b5aea97fafde23cd2c5a9a66b1a53edea0d1eae...,Pending
2,sample_pdf_3.pdf,..\data\input_pdfs\sample_pdf_3.pdf,0.06,8264bbd9bc2afc3c4ce9f04ba2cde4f82abff6f56ae446...,Pending

In [7]:
inventory.to_csv("../data/metadata/pdf_inventory.csv", index=False)
print("Inventory saved.")

Inventory saved.